add routes
aljke/react-lessons pull request #11
Opened 2023-10-23 13:54 UTC by aljke

<img width="1054" alt="image" src="https://github.com/aljke/react-lessons/assets/26021972/d42f491e-2064-4c53-bcec-caaa0d1740a3">

2023-10-28 18:59 UTC, volodymyr-kryvoshapov requested changes

2023-10-28 18:59 UTC, volodymyr-kryvoshapov commented on 06-routes/src/features/waiters/EditWaiter.tsx
> +  }
При сабміті форми спіннер треба розміщувати під формою, щоб інтерфейс не мігав. Зараз в тебе форма буде повністю зникати при сабміті.

2023-10-28 18:59 UTC, volodymyr-kryvoshapov commented on 06-routes/src/features/waiters/EditWaiter.tsx
> +  }
Помилку теж правильно розміщувати під формою

2023-10-28 18:59 UTC, volodymyr-kryvoshapov commented on 06-routes/src/features/waiters/EditWaiter.tsx
> +    navigate("/waiters");
Виходить так що ми не чекаемо поки збережеться юзер, а відразу робимо редірект. І в разі помилки юзер її не побачить.

Будьласка перероби ось так: 

```
const onSuccess = () =>  navigate("/waiters");

dispatch(saveWaiter(updatedWaiter, onSuccess))
``` 
Навігейт передай у вигляді колбека у saveWaiter санк

Ну або трай кеч прямо тут зробити:
```
try () {
  await dispatch(saveWaiter(updatedWaiter))
  navigate("/waiters")
} catch() {}
```

2023-10-30 18:24 UTC, aljke commented on 06-routes/src/features/waiters/EditWaiter.tsx
> +    navigate("/waiters");
fixed

2023-10-30 18:25 UTC, aljke commented on 06-routes/src/features/waiters/EditWaiter.tsx
> +  }
fixed

2023-10-30 19:42 UTC, volodymyr-kryvoshapov approved these changes

2023-11-01 18:11 UTC, merged